### PR TITLE
change import paths to kubernetes-sigs

### PR DESCRIPTION
**Pull request by jberkhahn**
per #2650

### CODE REVIEW

**Comment by mszostok** [comment]
one thing is quite strange

When you click the Details button for **pull-service-catalog-integration** then the URL is:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_service-catalog/2652/pull-service-catalog-integration/1136353016471883776/

and proper link should be:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_service-catalog/2652/pull-service-catalog-integration/1136353016471883776/

Same situation for the **pull-service-catalog-xbuild** job. Only the **pull-service-catalog-unit** has the correct URL

I've check also the [TEST PR](https://github.com/kubernetes-sigs/service-catalog/pull/2649) and there is the same situation, so changes introduced in that PR didn't break that. Maybe sth is incorrect in test-infra repo config?

**Comment by mszostok** [comment]
**ok found it!**  after a 2h of debugging...

the problem is that we are using the old approach for pushing the logs. Service Catalog jobs are using the [boostrap.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py) script. This script checkouts the repo and after all also pushes the logs into GCS. But link to job logs are set by the  plank which has the `job_url_template` variable: https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L2

If you will check that tmpl in details you will find such `if` statements:
```go
{{if .Spec.Refs}}
    {{if ne .Spec.Refs.Org ""}}
        {{if ne .Spec.Refs.Org "kubernetes"}}/
            {{if and (eq .Spec.Refs.Org "kubernetes-sigs") (ne .Spec.Refs.Repo "poseidon")}}
				sigs.k8s.io
            {{else}}
				{{.Spec.Refs.Org}}
            {{end}}
        _{{.Spec.Refs.Repo}}
        {{else if ne .Spec.Refs.Repo "kubernetes"}}
			/{{.Spec.Refs.Repo}}
		{{end}}
    {{end}}
{{end}}
```

so unfortunately in templeate, we are entering in such if statement
`{{if and (eq .Spec.Refs.Org "kubernetes-sigs") (ne .Spec.Refs.Repo "poseidon")}}` 
and the **sigs.k8s.io** suffix is added instead of **{{.Spec.Refs.Org}}**, where the logs are actually pushed by the [boostrap.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py) script.

The problem is that the logic decoupled, one tool is pushing the logs, other is setting the logs URL in ProwJob status and the logic is not the same.

The [boostrap.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py) script is already deprecated. To solve that problem we should use the `decorator` pattern, same as we have for the **pull-service-catalog-unit** job. Thanks to that decorator will take care both for pushing the logs and setting proper URL in ProwJob status.


[Here](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#why-use-pod-utilities) is more info about deprecated [boostrap.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py)


Here is the PR to fixes that: 



----
so your PR LGTM

**Comment by jberkhahn** [comment]
yeah, i had just about figured that out myself. could you actually mark this as LGTM so it gets merged?

**Comment by jberkhahn** [comment]
huh, the travis tests aren't reporting back for some reason.

/retest

**Comment by jberkhahn** [comment]
had to rejigger things to get it to run the tests again, so it knocked your LGTM off

**Comment by MHBauer** [comment]
amazing

**Pull request merged**
