### PR TITLE
sheet

### PR DESCRIPTION
**Pull request by lovebaby979**
This PR is a  Documentation
   - [x] Documentation

update broken link

### CODE REVIEW

**Comment by mszostok** [comment]
Hi @lovebaby979, thanks for PR 🙂 

This file was vendored and cannot be edited manually. This problem first needs to be fixed in the upstream repository: https://github.com/kubernetes-sigs/yaml

Then we can vendor it once again with fixed file

**Comment by MHBauer** [comment]
Yes. Fix required upstream.

**Comment by lovebaby979** [comment]
@mhbauer

**Comment by MHBauer** [comment]
Correct action is to make a PR in https://github.com/kubernetes-sigs/yaml and then come back once there has been a release made with that change.
/close

**Pull request closed without merging**
