### PR TITLE
Switch from go dep to go modules

### PR DESCRIPTION
**Pull request by jberkhahn**
working through this. Currently barfing on a whole bunch of api violations. I think this is because the version of client-go the automated `go mod inti` gave me is wrong - we were on release v12.0 before. I can't seem to get it to give me that version.

### CODE REVIEW

**Comment by jberkhahn** [comment]
@mszostok 
-moved the repo-infra stuff into contrib/hack
-added a tools.go in contrib/tools for the codegen libs

**Comment by mszostok** [comment]
Fixes:

- Add `replace` directive in go.mod to ensure proper versions
    ```
    replace (
    	k8s.io/apiserver => k8s.io/apiserver v0.0.0-20200318004442-78eb7668314c
    	k8s.io/client-go => k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
    	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20190228160746-b3a7cee44a30
    	sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.2.0
    	sigs.k8s.io/structured-merge-diff => sigs.k8s.io/structured-merge-diff v0.0.0-20190302045857-e85c7b244fd2
    )
    ```


- Add `// +build` tag in tools.go

- Move comment under imports  in tools.go to get rid of lint error:
    ```
    contrib/tools/tools.go:25:2: a blank import should be only in a main or test package, or have a comment justifying it
    ```

- Add `verify-modules.sh` script which is replacement for `verify-vendor.sh`

- Remove vender + dep files

- Bump controller-runtime from 0.2.0-beta.0 to 0.2.0 

- Adjust go builds commands for tools to work with go mod

- Add  go script to verify the boilerplate - same as [kubeadm](https://github.com/kubernetes/kubeadm)

- Add `export GO111MODULE=on` to Makefile as unit-test uses Go 1.12 on our prow pipeline. PR to change it: https://github.com/kubernetes/test-infra/pull/17567

- Replace github.com/appscode/jsonpatchwith gomodules.xyz/jsonpatch/v2

**Comment by mszostok** [comment]
**Fixes:**

- Add `replace` directive in go.mod to ensure proper versions
    ```
    replace (
    	k8s.io/apiserver => k8s.io/apiserver v0.0.0-20200318004442-78eb7668314c
    	k8s.io/client-go => k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
    	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20190228160746-b3a7cee44a30
    	sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.2.0
    	sigs.k8s.io/structured-merge-diff => sigs.k8s.io/structured-merge-diff v0.0.0-20190302045857-e85c7b244fd2
    )
    ```


- Add `// +build` tag in tools.go

- Move comment under imports  in tools.go to get rid of lint error:
    ```
    contrib/tools/tools.go:25:2: a blank import should be only in a main or test package, or have a comment justifying it
    ```

- Add `verify-modules.sh` script which is replacement for `verify-vendor.sh`

- Remove vendor + dep files

- Bump controller-runtime from 0.2.0-beta.0 to 0.2.0 

- Adjust go builds commands for tools to work with go mod

- Add  go script to verify the boilerplate - same as [kubeadm](https://github.com/kubernetes/kubeadm)

- Add `export GO111MODULE=on` to Makefile as unit-test uses Go 1.12 on our prow pipeline. PR to change it: https://github.com/kubernetes/test-infra/pull/17567

- Replace github.com/appscode/jsonpatch with gomodules.xyz/jsonpatch/v2

- Change healthz endpoints to 8081, as new controller-runtime exposes metrics on 8080

- Change docker volume mount configuration to ensure better performance (https://docs.docker.com/docker-for-mac/osxfs-caching/)

**TODO:**

- update **Dependency Management** section in devguide.md

**Pull request merged**
