### PR TITLE
Add install instruction to create the namespace

### PR DESCRIPTION
**Pull request by jiayihu**
This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [x] Documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by jberkhahn** [comment]
This is uneeded as the helm chart creates the namespace.

**Comment by jiayihu** [comment]
That is not true, at least in Helm v3. It gives error if the namespace is not created before or if you don't pass the flag `--create-namespace`: https://github.com/helm/helm/pull/7648

**Comment by jberkhahn** [comment]
Ah, i wasn't aware that was SOP in helm3

**Comment by jberkhahn** [comment]
Could you move this down a tab, so it's included in 'helm 3 ' section?

**Comment by jiayihu** [comment]
Sure, it should be fine now although I'm not sure how the tabs thing works sorry. Also, to be quick, I edited using GH website so I hope you don't mind squashing the two commits.

**Comment by jberkhahn** [comment]
squashing the commits is fine, the tab things are for the docs website

in other news, it looks like our CI is blowing up so it might be a bit before this gets merged

**Comment by jiayihu** [comment]
Cyberpunk 2077 will still have robots failing because of a change in a Markdown file

**Comment by jberkhahn** [comment]
LOL

/lgtm
/approve

**Pull request merged**
