### PR TITLE
Improve travis build - skip redundant jobs

### PR DESCRIPTION
**Pull request by adamwalach**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
It fixes b

**Which issue(s) this PR fixes** 
Fixes https://github.com/kyma-project/kyma/issues/6007

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by adamwalach** [comment]
Release process is now controlled by `DEPLOY_TYPE` variable set in .travis file.
In case of commit to master "SC release *" jobs are triggered but they do not perform any action:
Screen Shot 2019-10-16 at 11 56 37
In the logs you can see:
Screen Shot 2019-10-16 at 12 20 47
Opposite situation(SC-master is skipped) occurs when new release is created:
Screen Shot 2019-10-16 at 12 36 05

**Comment by mszostok** [comment]
nice, btw. name per stage improved readability, good idea 👍

**Pull request merged**
