### PR TITLE
cleanup codebase and run gofmt

### PR DESCRIPTION
**Pull request by beautytiger**
This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
Cleanup codebase

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by mszostok** [comment]
Hi @beautytiger, thanks for the PR :)

but what kind of checks did you execute to perform such changes?
from 
```go
var service map[string]interface{}
service = services[0].(map[string]interface{})
```
to
```go
var service = services[0].(map[string]interface{})
```

**Comment by beautytiger** [comment]
@mszostok 
Oh, I manually run [staticcheck](https://staticcheck.io/docs/).
Thanks.

**Comment by mszostok** [comment]
Thanks @beautytiger 
I also created issue for cleaning up our verify stage: https://github.com/kubernetes-sigs/service-catalog/issues/2732

if you are interested then I can assist you with that:) 

/lgtm

**Pull request merged**
