### PR TITLE
Update ups-broker docs link to point to chart on github.

### LINKED ISSUE #2757: Issue with svc-cat.io/docs/charts/ups-broker
# Bug Report 

**What happened**:
Broken Link for  User Provided Service Broker
**What you expected to happen**:
It should redirect to correct URL
**How to reproduce it (as minimally and precisely as possible)**:
https://svc-cat.io/docs/cli/#use follow the url and try to open User Provided Service Broker linkk
**Anything else we need to know?**:
N/A

### PR DESCRIPTION
**Pull request by MirahImage**
This PR is a 
 - [ ] Feature Implementation
 - [X] Bug Fix
 - [X] Documentation

**What this PR does / why we need it**:
Fixes a broken link in the docs to the ups-broker helm chart. The existing version of the links points to the correct location in the git repository, but is incorrect when rendered into the web version of the docs. I have instead made the link point to the chart on GitHub. If there is a better option for pointing to the correct helm chart, I'm open to suggestions.

**Which issue(s) this PR fixes** 

Fixes #2757

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by MirahImage** [comment]
I believe the CLA bot picked up the wrong email from my account, as I have the signed the CLA with a different associated email. I have now made that the primary email on my github account, which should hopefully resolve the issue.

**Comment by mszostok** [comment]
Hi @MirahImage thanks for fixing that issue 👍 

/lgtm
/approve

**Pull request merged**
