### PR TITLE
support display and filter broker

### LINKED ISSUE #1749: Support displaying and filtering by broker in svcat
In cases where more than one broker is installed on a cluster, it would be helpful to display the associated broker in the list of classes/plans, for example:

```console
$ svcat get plans
        NAME                  CLASS                      BROKER                   DESCRIPTION
+------------------+--------------------------+----------------------+----------------------------------------+
  basic              azure-rediscache           osba                    Basic Tier, 250MB Cache
  redis-5-7          redis                      Minibroker              In-cluster installation of Redis 5.7
```

Additionally, a `--broker` flag filtering by broker, would be useful:
```console
$ svcat get classes --broker osba
            NAME                      BROKER                         DESCRIPTION
+--------------------------+---------------------------+--------------------------------------+
  azure-rediscache            osba                        Azure Redis Cache
                                                          (Experimental)
```

### PR DESCRIPTION
**Pull request by nzoueidi**
Support displaying and filtering by broker's name for svcat. 
This is still WIP.

Fixes #1749

### CODE REVIEW

**Comment by jberkhahn** [comment]
looks cool. you need to gofmt your changed files, though.

**Comment by nzoueidi** [comment]
Thanks! I will make sure to gofmt all my changes and push back again.

**Comment by jberkhahn** [comment]
/retest

looks like you have a bunch of actual errors, particularly in the pkg/svcat bit. It would also be nice if you could add tests for the existence of the flag and the passing through on the info in the cmd/svcat bits, as well as the actual filtering in the pkg/svcat part.

**Comment by jberkhahn** [comment]
any update on this?

**Comment by nzoueidi** [comment]
sorry for the delay @jberkhahn I was afk for several weeks. I will be working on this asap.

**Pull request closed without merging**
