### PR TITLE
Pass service instance name via ProvisionRequest context

### LINKED ISSUE #2532: FR: Can name of ServiceInstance be passed via ProvisionRequest context?
We are implementing a service broker for our CRDs. We see that name of ServiceInstance is not passed to ProvisionRequest. xref:  https://github.com/kubernetes-incubator/service-catalog/blob/37b874716ad709a175e426f5f5638322a600849f/pkg/controller/controller_instance.go#L2251 .

Is it possible to pass the name of the ServiceInstance via request to the service broker so that we can use the same name for our CRD?

### PR DESCRIPTION
**Pull request by taragu**
This PR is a 
 - [x] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
Pass service instance name via ProvisionRequest context

**Which issue(s) this PR fixes** 

Fixes #2532

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by jberkhahn** [comment]
looks like you needed to add this bit to some of the expected results in the integration tests?

**Comment by taragu** [comment]
@jberkhahn not sure why the tests were failing before. just ran them again and they passed

**Pull request merged**
