### PR TITLE
Adding helm3 command

### PR DESCRIPTION
**Pull request by prary**
Latest helm doesn't have --name flag

This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [ *] Documentation

### CODE REVIEW

**Comment by jberkhahn** [comment]
closing this in favor of #2761

**Comment by prary** [comment]
Hi @jberkhahn this PR has change in docs/walkthrough.md while #2761 has change in docs/install.md. Is the content of walktrough.md is generated through install.md?

**Pull request closed without merging**
