### PR TITLE
Remove unused api server implementation from master branch

### PR DESCRIPTION
**Pull request by mszostok**
**Description**

- This PRs removes all unnecessary code related to api-server which is not used anymore.

### CODE REVIEW

**Comment by mszostok** [comment]
travis is failing because of that issue: https://github.com/kubernetes-sigs/service-catalog/pull/2794

**Comment by MHBauer** [comment]
weird, travis page is green

**Comment by mszostok** [comment]
yes because I restarted that job manually after #2794 was merged to master 
Screen Shot 2020-05-09 at 00 05 27

**Comment by MHBauer** [comment]
Nice 👌

**Pull request merged**
