### PR TITLE
Fix typo in sc-design image

### LINKED ISSUE #2802: Typo in svc-cat.io/docs/design/ diagram
# Bug Report 

**What happened**:
Kubernetes is spelled "Kubernetess" in [this image](https://svc-cat.io/docs/images/sc-design.svg)
**What you expected to happen**:
Should be spelled as "Kubernetes"

### PR DESCRIPTION
**Pull request by alapidas**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [x] Documentation

**What this PR does / why we need it**:

This fixes a typo in a SVG used at https://svc-cat.io/docs/images/sc-design.svg

**Which issue(s) this PR fixes** 

Fixes #2802 

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by alapidas** [comment]
The SVG still appears to have a typo, please don't merge just yet

**Comment by jhvhs** [comment]
@alapidas That's because the name with a typo was in there twice, but only one typo was fixed.

**Pull request closed without merging**
