### PR TITLE
Add missing line to copy the svcat.exe into bin folder

### PR DESCRIPTION
**Pull request by Azadehkhojandi**
minor fix,  copy and paste of the PowerShell script should install Service Catalog CLI

 

This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [x] Documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by mszostok** [comment]
Hi @Azadehkhojandi 

Thanks for your PR!

please sign the CLA, without that we cannot merge your pr

**Comment by mszostok** [comment]
@Azadehkhojandi ping 🙂

The `cla/linuxfoundation` needs to be signed by you. You need to visit https://identity.linuxfoundation.org/projects/cncf and follow the instructions 🙂

**Comment by Azadehkhojandi** [comment]
@mszostok - I've signed CLA, how can I kick the check?
You are already authorized to contribute code to this project through your membership with CNCF - Microsoft.

**Comment by jberkhahn** [comment]
you just gotta wait for the bot to do it automatically
/lgtm
/approve

**Pull request merged**
