### PR TITLE
change controller finalizer back to kubernetes-incubator

### PR DESCRIPTION
**Pull request by jberkhahn**
as per the discussion in the meeting today

### CODE REVIEW

**Comment by mszostok** [comment]
found one thing:

you should also change the test data, it's mocked (both returned responses and golden files), so tests didn't catch that by IMO we should also rename that to do not confuse others. 

- [testdata](https://github.com/kubernetes-sigs/service-catalog/tree/master/cmd/svcat/testdata)

**Comment by jberkhahn** [comment]
@mszostok that should fix it

**Comment by MHBauer** [comment]
yea, this would definitely not be a compatible change.
Unfortunately, it probably means needing to have two code paths for a while.
Can brainstorm later if you want.

**Comment by mszostok** [comment]
@MHBauer during the SIG meeting we discuss to move this change to CRD migration tool. 

Here is the migration scenario from api-server to CRDs: https://github.com/kyma-incubator/service-catalog/blob/crds-migration/docs/migration-apiserver-to-crds.md#details-of-an-upgrade-and-migration

so we can add just one step to replace the finalizer name before saving resources into etcd and starting the new controller image.

That should be quite easy to do

**Pull request merged**
