### PR TITLE
Add option to execute e2e test both locally and CI

### PR DESCRIPTION
**Pull request by mszostok**
### Description

This PR enables e2e test on CI with Kuberentes 1.15

**Done:**
- Refactor code for running the e2e test. **Tests can be executed both on CI and locally**
  - running test locally:
     `make test-e2e`
      > **NOTE:** Docker is required for running e2e tests.
  - running on prow:
      https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-test-sc-e2e-job/1162418742185955328
- Remove the outdated Jenkins folder/scripts
- Update documentation about e2e tests
- Move all CI scripts to a single folder

**TODO:**
- Test changed Travis configuration on fork repo
- Add readme about current CI state (what is on Prow, what is on Travis etc) - will be done in separate PR

**This is a draft pull-request. Work still in progress.** 

Resolves https://github.com/kubernetes-sigs/service-catalog/issues/2659

### CODE REVIEW

**Comment by MHBauer** [comment]
Having never run kind before, my local run ends with:
```
#################################################################################################
# Fri Aug 16 15:30:55 PDT 2019
# - Loading Service Catalog image into cluster...
#################################################################################################

Error: Image: "service-catalog:canary" not present locally
Deleting cluster "kind-ci" ...
$KUBECONFIG is still set to use /Users/mhb/.kube/kind-config-kind-ci even though that file has been deleted, remember to unset it
make: *** [test-e2e] Error 1
```

**Comment by mszostok** [comment]
From logs I can see that cluster was created. What was the output of `- Building Service Catalog image from sources...`?

at the end, there should be `docker tag service-catalog-amd64:canary service-catalog:canary`

**Comment by MHBauer** [comment]
Added above, last line is 
`docker tag quay.io/kubernetes-service-catalog/service-catalog-amd64:canary quay.io/kubernetes-service-catalog/service-catalog:canary`

**Comment by mszostok** [comment]
ok, now I see the problem. You have the env REGISTRY configured.
see: https://github.com/kubernetes-sigs/service-catalog/blob/master/Makefile#L88-L95

I assumed that everyone will have that empty by default. To solve that issue I will change the
```
make service-catalog-image
```

into
```
env REGISTRY="" VERSION=canary ARCH=amd64 make service-catalog-image
```

so that will change that only for that particular command, thanks to that everyone will have the same setup.

thanks for finding that!

**Comment by MHBauer** [comment]
Oh, you're right, good catch! It's in my envrc, I probably don't need it set anymore.

``` shell
$ cat .envrc
# for running contrib/jenkins/test_walkthrough.sh
export REGISTRY=quay.io/kubernetes-service-catalog/
# export VERSION=v0.0.21
# export CLEANUP=true

# for make test-e2e
export SERVICECATALOGCONFIG=~/.kube/config
export KUBECONFIG=~/.kube/config
```

Giving it another go around.

**Comment by MHBauer** [comment]
Works good. I'm impressed.

/lgtm

**Comment by mszostok** [comment]
@MHBauer I only squashed commits, so ur `lgmt` was removed

**Pull request merged**
