### PR TITLE
switch CRDs to v1

### PR DESCRIPTION
**Pull request by shiresky**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

service-catalog chart contains CustomResourceDefinition manifests in API group apiextensions.k8s.io/v1beta1 that is deprecated in v1.16 in favor of apiextensions.k8s.io/v1.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by shiresky** [comment]
I'm affraid that tests would never pass because of
`protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111`
I have also encountered this communicate on K8s 1.19 but not on K8s 1.18.

**Comment by shiresky** [comment]
Can anybody comment if the issue is possible to resolve or there is Kubernetes code change necessary? @jberkhahn @jhvhs

**Comment by jhvhs** [comment]
@shiresky I'm looking into it. Will let you know once I figure it out.

**Comment by shiresky** [comment]
Hi @jhvhs ! Were you able to take a look? Any idea/conclusions?

**Comment by jhvhs** [comment]
> Hi @jhvhs ! Were you able to take a look? Any idea/conclusions?

I'm preparing this issue for the review process. I'm hoping that it won't take too long.

**Comment by liggitt** [comment]
/title switch CRDs to v1

To unblock this PR, you can add an `unapproved` annotation as described in https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md#what-to-do-if-you-accidentally-put-an-unapproved-api-in-a-protected-group

If you do that, include a link in the annotation value to an issue tracking the review request.

Regarding API review, it looks like there were some interactions with API reviewers in the early days regarding naming, etc, but I don't see an actual review of the schemas themselves:
* https://github.com/kubernetes-sigs/service-catalog/pull/1054#issuecomment-317460675
* https://github.com/kubernetes-sigs/service-catalog/issues/1080#issuecomment-322841232
* https://github.com/kubernetes-sigs/service-catalog/issues/1080#issuecomment-323500035
*  (https://github.com/kubernetes-sigs/service-catalog/issues/1080). Was an actual API review done on the alpha API?

cc @thockin @smarterclayton as API reviewers that interacted with these types in the past
cc @pmorie as early API driver, in case you have pointers to docs or PRs where review was done

Spelunking through API history:
* CRD manifests: https://github.com/kubernetes-sigs/service-catalog/commits/master/charts/catalog/templates/crds
* Promotion to v1beta1: https://github.com/kubernetes-sigs/service-catalog/pull/1356

**Comment by smarterclayton** [comment]
There was a lot of early review, but this has been dormant so long and the sig focus was lost and changed (I guess) that I'd have to revisit.  The APIs were specifically modelled to make interop with the service broker project - if that focus has changed it's not clear to me that the APIs still accomplish their goal so I think I'd need to see context about "where is service-catalog going" in order to review (which I would be happy to get involved in since the broader service-catalog mission has a lot of value as a generic api).

**Comment by jhvhs** [comment]
>  I think I'd need to see context about "where is service-catalog going" in order to review (which I would be happy to get involved in since the broader service-catalog mission has a lot of value as a generic api).

There were no changes to the service-catalog project direction, it is still an OSBAPI implementation. However, the SIG itself is planning to extend the scope within the same area in order to be able to go beyond OSBAPI - https://github.com/kubernetes/community/pull/5746

**Comment by shiresky** [comment]
Hi @jhvhs @smarterclayton 

what is the final decision on this PR?

**Comment by jintusebastian** [comment]
Hi @jhvhs @smarterclayton @shiresky

Any updates on this PR? and support for K8s v1.22?

**Comment by avirampi** [comment]
is there any thing new about the support for k8s v1.22

**Pull request closed without merging**
